name = "Beamlines"
uuid = "5bb90b03-0719-46b8-8ce4-1ef3afd3cd4b"
authors = ["Matt Signorelli <mgs255@cornell.edu> and contributors"]
version = "0.6.6"

[deps]
Accessors = "7d9f7c33-5ae7-4f3b-8dc6-eff91059b697"
AtomicAndPhysicalConstants = "5c0d271c-5419-4163-b387-496237733d8b"
EnumX = "4e289a0a-7415-4d19-859d-a7e5c4648b56"
FunctionWrappers = "069b7b12-0de2-55c6-9aab-29f3d0a68a2e"
GTPSA = "b27dd330-f138-47c5-815b-40db9dd9b6e8"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
MacroTools = "1914dd2f-81c6-5fcd-8719-6d5c9610ff09"
OrderedCollections = "bac558e1-5e72-5ebc-8fee-abe8a469f55d"
PythonCall = "6099a3de-0909-46bc-b1f4-468b9a2dfc0d"
StaticArrays = "90137ffa-7385-5640-81b9-e52037218182"

[weakdeps]
PythonCall = "6099a3de-0909-46bc-b1f4-468b9a2dfc0d"

[extensions]
BeamlinesPythonCallExt = "PythonCall"

[compat]
Accessors = "0.1.42"
AtomicAndPhysicalConstants = "0.8.0"
EnumX = "1.0.5"
FunctionWrappers = "1.1.3"
GTPSA = "1.4"
MacroTools = "0.5.16"
OrderedCollections = "1.8.1"
PythonCall = "0.9.26"
StaticArrays = "1.9.13"
julia = "1.10"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
